name: Build Hello world
on:
  push:
      branches: [master]

jobs:
    build:
      runs-on: ubuntu-latest
      container:
        image: 'docker/Dockerfile'
      steps:
        - name: Build
          uses: jf002/docker-action-build
          with:
            entrypoint: /opt/build.sh
            args: all