name: Build Hello world
on:
  push:
      branches: [master]

jobs:
    build:
      runs-on: ubuntu-latest
      container:
        image: jf002/docker-action-build
      steps:
        - name: Build
          shell: bash
          run: |
            echo "coucou"