name: Build Hello world
on:
  push:
      branches: [master]

jobs:
    build:
      runs-on: ubuntu-latest
      container:
        image: jf002/docker-action-build
      steps:
        - name: Checkout source files
          uses: actions/checkout@v2
          with:
            submodules: recursive
        - name: Build
          shell: bash
          env:
            SOURCES_DIR: .
          run: |
            /opt/build.sh all
        - name: Upload artifacts
          uses: actions/upload-artifact@v2
          with:
            name: HelloWorld
            path: build/*