name: Build Hello world
on:
  push:
      branches: [master]

jobs:
    build:
      runs-on: ubuntu-latest
      container:
        image: jf002/docker-action-build
      steps:
        - name: Checkout source files
          uses: actions/checkout@v2
          with:
            submodules: recursive
        - name: Build
          shell: bash
          run: |
            /opt/build.sh all